const KEY="body_factory_v13";
const base=[["Куриная грудка",165,31],["Яйцо",157,13],["Творог 5%",121,17],["Греческий йогурт",73,10],["Рис варёный",130,2.7],["Гречка варёная",110,4.2],["Овсянка сухая",370,13],["Картофель варёный",82,2],["Макароны варёные",158,5.8],["Хлеб",250,8],["Банан",89,1.1],["Яблоко",52,.3],["Овощи",35,1.5],["Лосось",208,20],["Тунец",116,26],["Говядина",187,26],["Сыр",350,25],["Орехи",600,18],["Оливковое масло",884,0],["Шоколад",540,7]];
let db=JSON.parse(localStorage.getItem(KEY)||"null");
if(!db){db={goal:"lose",start:90,target:80,deficit:500,nextId:100,products:base.map((x,i)=>({id:i+1,name:x[0],kcal:x[1],protein:x[2],custom:false})),food:[],days:[],coins:0,rewards:[],tasks:{}}}else migrate();
function migrate(){db.goal=db.goal||"lose";db.start=+db.start||90;db.target=+db.target||80;db.deficit=+db.deficit||500;db.products=db.products||[];db.food=db.food||[];db.days=db.days||[];db.coins=+db.coins||0;db.rewards=db.rewards||[];db.tasks=db.tasks||{};db.nextId=db.nextId||100;save()}
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function today(){return new Date().toISOString().slice(0,10)}function prod(id){return db.products.find(p=>p.id==id)}function foodDate(d){return db.food.filter(x=>x.date===d)}function kcal(e){let p=prod(e.productId);return p?e.grams*p.kcal/100:0}function protein(e){let p=prod(e.productId);return p?e.grams*p.protein/100:0}function day(d){return db.days.find(x=>x.date===d)}function latest(){return db.days.slice().sort((a,b)=>a.date.localeCompare(b.date)).at(-1)}function weight(){return latest()?.weight||db.start}function progress(){let span=Math.abs(db.target-db.start),delta=db.goal==="lose"?db.start-weight():weight()-db.start;return span?Math.max(0,Math.min(1,delta/span)):1}function remaining(){return db.goal==="lose"?Math.max(0,weight()-db.target):Math.max(0,db.target-weight())}function level(){return Math.min(11,1+Math.floor(progress()*10))}function toast(t){let x=document.getElementById("toast");x.textContent=t;x.style.display="block";setTimeout(()=>x.style.display="none",1600)}
const TASKS=[{id:"weight",name:"Контроль системы",desc:"Внести вес за день",reward:10,check:d=>!!day(d)},{id:"food",name:"Контроль питания",desc:"Записать продукт",reward:15,check:d=>foodDate(d).length>0},{id:"steps",name:"Разогрев производства",desc:"8 000 шагов",reward:20,check:d=>(day(d)?.steps||0)>=8000},{id:"strength",name:"Модернизация корпуса",desc:"Силовая тренировка",reward:25,check:d=>!!day(d)?.strength}];
function claim(date,type){let k=date+"_"+type,t=TASKS.find(x=>x.id===type);if(!t||db.tasks[k])return;if(t.check(date)){db.tasks[k]=1;db.coins+=t.reward;db.rewards.unshift({date,amount:t.reward,text:t.name});save();toast("+"+t.reward+" ₿");render("home")}else toast("Задание пока не выполнено")}
function home(a){let p=Math.round(progress()*100),dir=db.goal==="lose"?"🔥 Похудение":"💪 Набор веса",tasks=TASKS.map(t=>{let ok=t.check(today()),done=db.tasks[today()+"_"+t.id];return `<div class="item row between"><div><b>${t.name}</b><br><span class="muted">${t.desc} • +${t.reward} ₿</span></div><button ${(!ok||done)?"disabled":""} onclick="claim('${today()}','${t.id}')">${done?"Получено":ok?"Забрать":"Не готово"}</button></div>`}).join("");a.innerHTML=`<div class="grid"><div class="card stat">🎯 Цель<b>${dir}</b></div><div class="card stat">⚖️ Вес<b>${weight().toFixed(1)} кг</b></div><div class="card stat">📊 Прогресс<b>${p}%</b></div><div class="card stat">💰 Валюта<b>${db.coins} ₿</b></div></div><div class="card"><div class="title">${dir}</div>Старт: ${db.start.toFixed(1)} кг → Цель: ${db.target.toFixed(1)} кг<div class="progress" style="margin-top:10px"><div style="width:${p}%"></div></div><p class="muted">${remaining().toFixed(1)} кг до цели • Уровень ${level()}</p></div><div class="card"><div class="title">🎯 Задания на сегодня</div>${tasks}</div><div class="card"><div class="title">💰 Награды</div>${db.rewards.slice(0,8).map(r=>`<div class="item">+${r.amount} ₿ — ${esc(r.text)} <span class="muted">(${r.date})</span></div>`).join("")||'<div class="empty">Пока нет наград</div>'}</div>`}
function food(a){let d=today(),list=foodDate(d).slice().reverse().map(e=>{let p=prod(e.productId);return `<div class="item row between"><div><b>${esc(p?.name||"Удалённый продукт")}</b><br><span class="muted">${e.grams} г • ${Math.round(kcal(e))} ккал • ${protein(e).toFixed(1)} г белка</span></div><button class="danger" onclick="delFood(${e.id})">Удалить</button></div>`}).join("");a.innerHTML=`<div class="card"><div class="title">🍽️ Питание</div><label>Дата</label><input id="fd" type="date" value="${d}"><label>Продукт</label><select id="fp">${db.products.slice().sort((x,y)=>x.name.localeCompare(y.name)).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("")}</select><label>Граммы</label><input id="fg" type="number" min="1" value="100"><button class="full" onclick="addFood()">Добавить</button></div><div class="card"><div class="title">Записи за выбранную дату</div><div id="foodList">${list||'<div class="empty">Пока пусто</div>'}</div></div>`}
function addFood(){let d=fd.value||today(),g=+fg.value,id=+fp.value;if(!g)return;db.food.push({id:Date.now(),date:d,productId:id,grams:g});save();toast("Еда добавлена");render("food")}
function delFood(id){db.food=db.food.filter(x=>x.id!==id);save();render("food")}
function products(a){a.innerHTML=`<div class="card"><div class="row between"><div class="title">🍎 Склад</div><button onclick="productDialog.showModal()">+ Добавить</button></div><span class="muted">${db.products.length} продуктов</span></div><div class="card">${db.products.slice().sort((x,y)=>x.name.localeCompare(y.name)).map(p=>`<div class="item row between"><div><b>${esc(p.name)}</b>${p.custom?' <span class="muted">• свой</span>':''}<br><span class="muted">${p.kcal} ккал • ${p.protein} г белка / 100 г</span></div>${p.custom?`<button class="danger" onclick="delProduct(${p.id})">Удалить</button>`:""}</div>`).join("")}</div>`}
function addProduct(e){e.preventDefault();let n=pn.value.trim(),k=+pk.value,p=+pp.value;if(!n)return false;db.products.push({id:db.nextId++,name:n,kcal:k,protein:p,custom:true});save();productDialog.close();e.target.reset();toast("Продукт добавлен");render("products");return false}
function delProduct(id){if(!confirm("Удалить продукт и его записи питания?"))return;db.products=db.products.filter(p=>p.id!==id);db.food=db.food.filter(e=>e.productId!==id);save();render("products")}
function diary(a){let rows=db.days.slice().sort((x,y)=>y.date.localeCompare(x.date)).map(d=>`<div class="item row between"><div><b>${d.date} — ${d.weight.toFixed(1)} кг</b><br><span class="muted">${d.steps||0} шагов • силовая: ${d.strength?"да":"нет"}</span></div><button class="danger" onclick="delDay('${d.date}')">Удалить</button></div>`).join("");a.innerHTML=`<div class="card"><div class="title">📖 Дневник</div><label>Дата</label><input id="dd" type="date" value="${today()}"><label>Вес, кг</label><input id="dw" type="number" step=".1" placeholder="${weight().toFixed(1)}"><label>Шаги</label><input id="ds" type="number" min="0" value="8000"><label><input id="dst" type="checkbox" style="width:auto"> Силовая тренировка</label><button class="full" onclick="saveDay()">Сохранить запись</button></div><div class="card"><div class="title">История веса</div>${rows||'<div class="empty">Нет записей</div>'}</div>`}
function saveDay(){let d=dd.value||today(),w=+dw.value,s=+ds.value||0;if(!w)return toast("Введи вес");db.days=db.days.filter(x=>x.date!==d);db.days.push({date:d,weight:w,steps:s,strength:dst.checked});save();toast("Запись сохранена");render("diary")}
function delDay(d){if(!confirm("Удалить запись за "+d+"?"))return;db.days=db.days.filter(x=>x.date!==d);save();render("diary")}
function settings(a){a.innerHTML=`<div class="card"><div class="title">🎯 Цель кампании</div><label>Режим</label><select id="goal"><option value="lose" ${db.goal==="lose"?"selected":""}>🔥 Похудеть</option><option value="gain" ${db.goal==="gain"?"selected":""}>💪 Набрать вес</option></select><label>Стартовый вес, кг</label><input id="ss" type="number" step=".1" value="${db.start}"><label>Целевой вес, кг</label><input id="st" type="number" step=".1" value="${db.target}"><label>Целевой дефицит, ккал</label><input id="sd" type="number" value="${db.deficit}"><button class="full" onclick="saveSettings()">Сохранить</button></div><div class="card"><div class="title">💾 Данные</div><button class="secondary full" onclick="exportData()">Экспортировать резервную копию</button><button class="secondary full" onclick="document.getElementById('imp').click()">Импортировать резервную копию</button><input id="imp" type="file" accept=".json" style="display:none" onchange="importData(event)"><button class="danger full" onclick="resetAll()">🗑️ Удалить ВСЕ данные</button></div>`}
function saveSettings(){let s=+ss.value,t=+st.value;if(!s||!t||s<=0||t<=0)return toast("Проверь значения");db.goal=goal.value;db.start=s;db.target=t;db.deficit=+sd.value||500;save();toast("Настройки сохранены");render("home")}
function exportData(){let b=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="body-factory-backup.json";a.click()}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.products||!x.food||!x.days)throw 0;db=x;migrate();toast("Восстановлено");render("home")}catch{toast("Ошибка резервной копии")}};r.readAsText(f)}
function resetAll(){if(!confirm("Удалить ВСЕ данные: вес, питание, продукты, задания, валюту и настройки?"))return;localStorage.removeItem(KEY);location.reload()}
function render(s="home"){document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.s===s));({home,food,products,diary,settings})[s](document.getElementById("app"))}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>render(b.dataset.s));if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js?v=3").then(r=>r.update()).catch(()=>{});render();