
const KEY="body_factory_pwa_v1";const defaults=[["Куриная грудка",165,31],["Яйцо",157,13],["Творог 5%",121,17],["Греческий йогурт",73,10],["Рис варёный",130,2.7],["Гречка варёная",110,4.2],["Овсянка сухая",370,13],["Картофель варёный",82,2],["Макароны варёные",158,5.8],["Хлеб",250,8],["Банан",89,1.1],["Яблоко",52,.3],["Лосось",208,20],["Тунец",116,26],["Говядина",187,26],["Сыр",350,25],["Орехи",600,18],["Оливковое масло",884,0],["Шоколад",540,7]];
let db=JSON.parse(localStorage.getItem(KEY)||"null")||{start:90,target:80,deficit:500,nextId:100,products:defaults.map((x,i)=>({id:i+1,name:x[0],kcal:x[1],protein:x[2],custom:false})),food:[],days:[]};
const save=()=>localStorage.setItem(KEY,JSON.stringify(db)),today=()=>new Date().toISOString().slice(0,10),P=id=>db.products.find(p=>p.id==id),esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const kcal=e=>P(e.productId)?e.grams*P(e.productId).kcal/100:0,prot=e=>P(e.productId)?e.grams*P(e.productId).protein/100:0,TF=()=>db.food.filter(e=>e.date===today()),TW=()=>db.days.slice().sort((a,b)=>a.date.localeCompare(b.date)).at(-1)?.weight||db.start;
function toast(t){let x=document.getElementById("toast");x.textContent=t;x.style.display="block";setTimeout(()=>x.style.display="none",1400)}
function render(s="home"){document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.s===s));({home,food,products,diary,settings})[s]()}
function home(){let w=TW(),lost=Math.max(0,db.start-w),rem=Math.max(0,w-db.target),pr=db.start===db.target?0:Math.max(0,Math.min(1,lost/(db.start-db.target))),lvl=Math.floor(pr*10)+1;app.innerHTML=`<div class="grid"><div class="card stat">⚖️ Вес<b>${w.toFixed(1)} кг</b></div><div class="card stat">📉 Сброшено<b>${lost.toFixed(1)} кг</b></div><div class="card stat">🎯 Осталось<b>${rem.toFixed(1)} кг</b></div><div class="card stat">🏆 Уровень<b>${lvl} / 11</b></div></div><div class="card"><div class="title">Прогресс кампании</div><div class="progress"><div style="width:${pr*100}%"></div></div><div class="muted">${Math.round(pr*100)}%</div></div><div class="card"><div class="title">🍽️ Сегодня</div><b>${Math.round(TF().reduce((s,e)=>s+kcal(e),0))} ккал</b><br>${Math.round(TF().reduce((s,e)=>s+prot(e),0))} г белка</div>`}
function food(){let rows=TF().slice().reverse().map(e=>{let p=P(e.productId);return p?`<div class="item row between"><div><b>${esc(p.name)}</b><br><span class="muted">${e.grams} г • ${Math.round(kcal(e))} ккал • ${prot(e).toFixed(1)} г белка</span></div><button class="danger" onclick="delFood(${e.id})">Удалить</button></div>`:""}).join("");app.innerHTML=`<div class="card"><div class="title">🍽️ Добавить еду</div><label>Продукт</label><select id="fp">${db.products.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("")}</select><label>Граммы</label><input id="fg" type="number" value="100" min="1"><button class="full" onclick="addFood()">Добавить</button></div><div class="card"><div class="title">Сегодня</div>${rows||'<div class="empty">Пока пусто</div>'}</div>`}
function addFood(){let g=+fg.value;if(g<=0)return;db.food.push({id:Date.now(),date:today(),productId:+fp.value,grams:g});save();toast("Еда добавлена");render("food")}
function delFood(id){if(!confirm("Удалить эту запись питания?"))return;db.food=db.food.filter(e=>e.id!==id);save();render("food")}
function products(){let rows=db.products.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<div class="item row between"><div><b>${esc(p.name)}</b>${p.custom?" <span class=muted>• свой</span>":""}<br><span class=muted>${p.kcal} ккал / 100 г • ${p.protein} г белка</span></div>${p.custom?`<button class=danger onclick="delProduct(${p.id})">Удалить</button>`:""}</div>`).join("");app.innerHTML=`<div class="card"><div class="row between"><div class="title">🍎 Склад</div><button onclick="pd.showModal()">+ Добавить</button></div><div class="muted">Своих продуктов: ${db.products.filter(p=>p.custom).length}</div></div><div class="card">${rows}</div>`}
function createProduct(e){e.preventDefault();let n=pn.value.trim(),k=+pk.value,p=+pp.value;if(!n||k<0||p<0)return false;db.products.push({id:db.nextId++,name:n,kcal:k,protein:p,custom:true});save();pd.close();e.target.reset();toast("Продукт сохранён");render("products");return false}
function delProduct(id){if(!confirm("Удалить продукт? Связанные записи питания тоже будут удалены."))return;db.products=db.products.filter(p=>p.id!==id);db.food=db.food.filter(e=>e.productId!==id);save();render("products")}
function diary(){let rows=db.days.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(d=>`<div class="item row between"><div><b>${d.date}: ${d.weight.toFixed(1)} кг</b><br><span class=muted>${d.steps||0} шагов • силовая: ${d.strength?"да":"нет"}</span></div><button class=danger onclick="delDay('${d.date}')">Удалить</button></div>`).join("");app.innerHTML=`<div class="card"><div class="title">📖 Дневник</div><label>Вес, кг</label><input id="dw" type="number" step=".1" placeholder="${TW().toFixed(1)}"><label>Шаги</label><input id="ds" type="number" value="8000"><label><input id="dst" type="checkbox" style="width:auto"> Силовая тренировка</label><button class="full" onclick="saveDay()">Сохранить день</button></div><div class="card"><div class="title">История веса</div>${rows||'<div class=empty>Записей пока нет</div>'}</div>`}
function saveDay(){let w=+dw.value;if(w<=0){toast("Введи вес");return}db.days=db.days.filter(d=>d.date!==today());db.days.push({date:today(),weight:w,steps:+ds.value||0,strength:dst.checked});save();toast("День сохранён");render("diary")}
function delDay(date){if(!confirm("Удалить запись веса за "+date+"?"))return;db.days=db.days.filter(d=>d.date!==date);save();render("diary")}
function settings(){app.innerHTML=`<div class="card"><div class="title">⚙️ Кампания</div><label>Стартовый вес</label><input id="ss" type="number" step=".1" value="${db.start}"><label>Целевой вес</label><input id="st" type="number" step=".1" value="${db.target}"><label>Дефицит, ккал</label><input id="sd" type="number" value="${db.deficit}"><button class="full" onclick="saveSettings()">Сохранить</button></div><div class="card"><div class="title">💾 Данные</div><button class="secondary full" onclick="exportData()">Экспортировать резервную копию</button><button class="secondary full" onclick="document.getElementById('imp').click()">Импортировать резервную копию</button><input id="imp" type="file" accept=".json" style="display:none" onchange="importData(event)"><button class="danger full" onclick="resetData()">Удалить ВСЕ данные</button></div>`}
function saveSettings(){if(+ss.value<=0||+st.value<=0||+sd.value<=0){toast("Проверь значения");return}db.start=+ss.value;db.target=+st.value;db.deficit=+sd.value;save();toast("Сохранено");render("settings")}
function exportData(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:"application/json"}));a.download="body-factory-backup.json";a.click()}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.products||!x.food||!x.days)throw 0;db=x;save();toast("Данные восстановлены");render("settings")}catch{toast("Неверная резервная копия")}};r.readAsText(f)}
function resetData(){if(!confirm("Удалить ВСЕ данные? Это нельзя отменить."))return;localStorage.removeItem(KEY);location.reload()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>render(b.dataset.s));if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js?v=3").then(r=>r.update()).catch(()=>{});render();
